FROM alpine

WORKDIR /app

COPY ./ttyd/ttyd ./ttyd

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories && \
    apk update && \
    apk add --no-cache openssh-client && \
    chmod +x ttyd
